FROM wordpress:4.8-apache
COPY status.conf /etc/apache2/mods-available/status.conf
#COPY 000-default.conf /etc/apache2/sites-enabled/000-default.conf
COPY htaccess /htaccess
# cp /htaccess /var/www/html/.htaccess
