version: '3.7'
services:
  tomcat:
    container_name: tomcat
    build:
      context: .
    image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/tomcat:20240118
    environment:
      - TARGET_URL=http://nginx/
      - DD_AGENT_HOST=datadog-agent
    ports:
      - 8083:8080
    labels:
      com.datadoghq.ad.logs: >-
        [{"source": "java", "service": "tomcat"}]

networks:
  default:
    name: datadog
    external: true
