version: '3.7'
services:
  nginx:
    image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/nginx:3
    build:
      context: nginx
      args:
        image: "nginx:1.25.2-alpine"
      dockerfile: Dockerfile
    ports:
      - 11080:80

  php-fpm:
    image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/php-fpm:with-ddtracer-6
    build:
      context: .
      args:
        image: "php:8.1.23-fpm-bullseye"
      dockerfile: Dockerfile

networks:
  default:
    name: datadog
    external: true
