version: '3.7'
services:
  nginx:
    container_name: nginx
    build:
      context: nginx
      args:
        image: nginx:1.25.2-alpine
      dockerfile: Dockerfile
    ports:
      - 11080:80
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=nginx

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      args:
        image: php:8.1.23-fpm-bullseye
      dockerfile: Dockerfile
    environment:
      - CURL_TARGET_URL
      - CURL_COUNT=1
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=php-fpm
    command:
      - /bin/sh
      - -c
      - php-fpm 2>&1

networks:
  default:
    name: datadog
    external: true
