version: '3.7'
services:
  nginx:
    build:
      context: nginx
      args:
        image: "nginx:1.25.2-alpine"
      dockerfile: Dockerfile
    ports:
      - 11080:80
    environment:
      - DD_AGENT_HOST=datadog-agent

  php-fpm:
    build:
      context: .
      args:
        image: "php:8.1.23-fpm-bullseye"
      dockerfile: Dockerfile
    environment:
      - CURL_COUNT=1
      - DD_AGENT_HOST=datadog-agent

networks:
  default:
    name: datadog
    external: true
