version: '3.7'
services:
  nginx:
    container_name: nginx
    image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/nginx:20241002
    build:
      context: nginx
      args:
        image: nginx:1.27.0-alpine
      dockerfile: Dockerfile
    ports:
      - 81:81
      - 82:80
    environment:
      - PHP_FPM_ADDR=php-fpm:9000
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=nginx
      - DD_ENV=masafumi_kashiwagi
      - DD_VERSION=1.0
      - DD_TRACE_DEBUG=true
      - DD_TAGS=team:masafumi evn2:docker
    labels:
      com.datadoghq.ad.checks: '{"nginx": {"instances": [{"nginx_status_url": "http://nginx:81/nginx_status/"}]}}'
  php-fpm:
    container_name: php-fpm
    image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/php-fpm:20241002
    build:
      context: .
      args:
        image: php:8.1.23-fpm-bullseye
      dockerfile: Dockerfile
    environment:
      - CURL_TARGET_URL=http://wordpress/
      - CURL_COUNT=1
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=php-fpm
      - DD_ENV=masafumi_kashiwagi
      - DD_VERSION=1.0
      - DD_TRACE_DEBUG=true
      - DD_TAGS=team:masafumi evn2:docker
#      - DD_INSTRUMENTATION_TELEMETRY_ENABLED=0
    volumes:
      - ./src:/usr/share/nginx/html/
    labels:
      com.datadoghq.ad.checks: '{"php_fpm": {"instances": [{"status_url": "http://nginx/status", "ping_url": "http://nginx/ping", "ping_reply": "pong"}]}}'

networks:
  default:
    name: datadog
    external: true
