version: '3.7'
services:
  nginx:
    container_name: nginx
    image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/nginx:20231220-2
    build:
      context: nginx
      args:
        image: nginx:1.25.2-alpine
      dockerfile: Dockerfile
    ports:
      - 81:81
      - 82:80
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=nginx
    labels:
      com.datadoghq.ad.checks: '{"nginx": {"instances": [{"nginx_status_url": "http://nginx:81/nginx_status/"}]}}'

  php-fpm:
    container_name: php-fpm
    image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/php-fpm:20231220-1
    build:
      context: .
      args:
        image: php:8.1.23-fpm-bullseye
      dockerfile: Dockerfile
    environment:
      - CURL_TARGET_URL
      - CURL_COUNT=1
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=php-fpm
    volumes:
      - ./src:/usr/share/nginx/html/
    # command:
    #   - /bin/sh
    #   - -c
    #   - php-fpm 2>&1

networks:
  default:
    name: datadog
    external: true
