version: '3.7'
services:
  snmp:
    container_name: snmp
    image: "tandrup/snmpsim:latest"
    ports:
      - "161:161/udp"
    volumes:
      - ./data/:/usr/local/share/snmpsim/data
<<<<<<< HEAD
=======
    command:
      - /bin/sh
      - -c
      - snmpsimd.py --agent-udpv4-endpoint=0.0.0.0:161 --process-user=snmpsim --process-group=nogroup 2>&1
>>>>>>> refs/remotes/origin/main
#    logging:
#      driver: "syslog"
#      options:
#        syslog-facility: daemon
#        tag: container/{{.Name}}/{{.ID}}
#        syslog-address: "udp:/localhost:514"

networks:
  default:
    name: datadog
    external: true
