version: '3.8'
services:
  weblogic:
    image: container-registry.oracle.com/middleware/weblogic:12.2.1.4
    ports:
      - "7001:7001"
      - "9002:9002"
      - "9090:9090"
    volumes:
      - .:/u01/oracle/properties
    environment:
      # Set environment variables as needed
      - JAVA_OPTIONS=-Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.authenticate=false -Djavax.management.builder.initial=weblogic.management.jmx.mbeanserver.WLSMBeanServerBuilder
      - DD_ENV=masafumi_kashiwagi
      - DD_TAGS=team:masafumi env2:docker
    container_name: weblogic

networks:
  default:
    name: datadog
    external: true
