version: '3.7'
services:
  datadog-agent:
    container_name: datadog-agent
    image: my-datadog-agent:7.50.1
    build:
      args:
        image: datadog/agent:7.50.1
      context: .
      dockerfile: Dockerfile
    #image: datadog/agent:latest
    ports:
      - 18125:8125/udp
      - 18126:8126/tcp
    environment:
      - DD_API_KEY
      - DD_HOSTNAME=aws-docker
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
#      - DD_APM_RECEIVER_SOCKET=/opt/datadog/apm/inject/run/apm.socket
#      - DD_DOGSTATSD_SOCKET=/opt/datadog/apm/inject/run/dsd.socket
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_SYSTEM_PROBE_NETWORK_ENABLED=true
    volumes:
#      - /opt/datadog/apm:/opt/datadog/apm
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /sys/kernel/debug:/sys/kernel/debug
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
      - IPC_LOCK
      - CHOWN
    security_opt:
      - apparmor:unconfined

networks:
  default:
    name: datadog
    external: true
