version: '3.7'
services:
  jmx-test:
    build:
      context: .
    environment:
      - TARGET_URL
      - DD_AGENT_HOST=datadog-agent
    labels:
      com.datadoghq.ad.logs: >-
        [{"source": "java", "service": "jmx-test"}]
  datadog-agent:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY
      - DD_HOSTNAME
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
