version: '3.7'
services:
  oracle-db:
    container_name: oracle-db
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      - ORACLE_PWD=password
      - DD_ENV=masafumi_kashiwagi
      - DD_TAGS=team:masafumi env2:docker
    labels:
      com.datadoghq.ad.checks: '{"oracle": {"instances": [{"dbm": true, "server": "oracle-db:1521", "service_name": "XE", "username": "datadog", "password": "datadog"}]}}'
    volumes:
      - ./startup_script:/opt/oracle/scripts/startup
      
networks:
  default:
    name: datadog
    external: true
