version: '3.1'

services:
  wordpress:
    container_name: wordpress
    image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/wordpress:20240118
    build:
      context: wordpress
      args:
        image: wordpress:php8.3-apache
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      DD_AGENT_HOST: datadog-agent
      DD_SERVICE: wordpress
      DD_ENV: dev
      DD_VERSION: 2.0
      DD_DBM_PROPAGATION_MODE: full
    volumes:
      - ./wordpress/status.conf:/etc/apache2/mods-available/status.conf
      - wordpress:/var/www/html
    labels:
      com.datadoghq.ad.checks: '{"apache": {"instances": [{"apache_status_url": "http://wordpress/server-status?auto"}]}}'
  db:
    container_name: wordpress_db
    image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/wordpress_db:20240118
    build:
      context: mysql
      args:
        image: mysql:8.0
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
    volumes:
      - ./mysql/default.sql:/docker-entrypoint-initdb.d/default.sql
      - ./mysql/my.cnf:/etc/my.cnf
      - db:/var/lib/mysql
    labels:
      com.datadoghq.ad.checks: '{"mysql": {"instances": [{"dbm": "true", "host": "wordpress_db", "port": "3306", "username": "datadog", "password": "datadog", "reported_hostname": "aws-docker", "query_samples": {"collection_interval": "0.1"}}]}}'

volumes:
  wordpress:
  db:

networks:
  default:
    name: datadog
    external: true
