version: '3.1'

services:

  wordpress:
    image: my-wordpress
    build:
      context: wordpress
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: masafumi-kashiwagi-aurora-mysql-instance-1-ap-northeast-1a.c3bw7kcbozbg.ap-northeast-1.rds.amazonaws.com
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
#     volumes:
#       - wordpress:/var/www/html

#   db:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_DATABASE: exampledb
#       MYSQL_USER: exampleuser
#       MYSQL_PASSWORD: examplepass
#       MYSQL_RANDOM_ROOT_PASSWORD: '1'
#     volumes:
#       - db:/var/lib/mysql

# volumes:
#   wordpress:
#   db:

networks:
  default:
    name: datadog
    external: true
