version: '3.7'
services:
  node:
    container_name: node
    build:
      context: .
    image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/node:20240220-2
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=node
      - DD_VERSION=1.0
      - DD_ENV=masafumi_kashiwagi
      - DD_TAGS=team:masafumi env2:docker
    ports:
      - 3000:3000

networks:
  default:
    name: datadog
    external: true
