version: '3.7'
services:
  apache-bench:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AB_TARGET=http://nginx/
      - AB_CONCURRENCY=4
      - AB_REQUESTS=10000
      
networks:
  default:
    name: datadog
    external: true
