---
version: "3.8"
services:
  httpservice1:
    image: "httpservice1-micrometer:0.0.1-SNAPSHOT-masa"
    build:
      context: httpservice1-micrometer
    depends_on:
      - jaeger
    ports:
      - "8080:8080"
    environment:
      - HTTPSERVICE2_ENDPOINT=http://httpservice2:8081
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://jaeger:4318/v1/traces
      - DD_SERVICE=httpservice1
      - DD_ENV=masafumi_kashiwagi
      - DD_VERSION=1.0
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_DEBUG=true
      - DD_TAGS=team:masafumi env2:docker
      #- DD_TRACE_PROPAGATION_STYLE=datadog

  httpservice2:
    image: "httpservice2-micrometer:0.0.1-SNAPSHOT-masa"
    build:
      context: httpservice2-micrometer
    depends_on:
      - jaeger
    ports:
      - "8081:8081"
    environment:
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://jaeger:4318/v1/traces
      - DD_SERVICE=httpservice2
      - DD_ENV=masafumi_kashiwagi
      - DD_VERSION=1.0
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_DEBUG=true
      - DD_TAGS=team:masafumi env2:docker
      #- DD_TRACE_PROPAGATION_STYLE=datadog

  jaeger:
    image: jaegertracing/all-in-one:1.53
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

networks:
  default:
    name: datadog
    external: true
