version: '3.7'
services:
  jmx-test:
    container_name: jmx-test
    build:
      context: .
    image: public.ecr.aws/b1o7r7e0/masafumi.kashiwagi/jmx-test:20240118
    environment:
      - TARGET_URL=http://tomcat:8080/sb
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=jmx-test
      - DD_ENV=docker
      - DD_VERSION=1.0
    labels:
      com.datadoghq.ad.logs: >-
        [{"source": "java", "service": "jmx-test"}]

networks:
  default:
    name: datadog
    external: true
