version: '3.7'
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
    labels:
      com.datadoghq.ad.checks: '{"sqlserver": {"instances": [{"dbm": true, "host": "sqlserver,1433", "username": "datadog", "password": "Datad0gs", "connector": "odbc", "driver": "{ODBC Driver 18 for SQL Server}", "dsn": "datadog", "connection_string": "TrustServerCertificate=yes;"}]}}'
    ports:
      - 1433:1433
  sqlserver-client:
    container_name: sqlserver-client
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
    depends_on:
      - sqlserver
    entrypoint: /datadog/setup.sh
    volumes:
      - ./datadog:/datadog
      
networks:
  default:
    name: datadog
    external: true
