version: "3.7"
services:
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    labels:
      com.datadoghq.ad.checks: >-
        {"kafka_consumer":{"instances":[{"kafka_connect_str":"kafka:9092","monitor_unlisted_consumer_groups":true}]}}
  kafka-producer:
    image: confluentinc/cp-kafka
    container_name: kafka-producer
    environment:
      KAFKA_ADDR: kafka:9092
    depends_on:
      - kafka
    command:
    - sh
    - -c
    - for i in $$(seq 1 1000);do echo $$i;done | kafka-console-producer --topic quickstart-events1 --bootstrap-server $${KAFKA_ADDR}
  kafka-consumer:
    image: confluentinc/cp-kafka
    container_name: kafka-consumer
    environment:
      KAFKA_ADDR: kafka:9092
    depends_on:
      - kafka-producer
    command:
    - sh
    - -c
    - kafka-console-consumer --topic quickstart-events1 --bootstrap-server $${KAFKA_ADDR} --from-beginning --group consumer-group1
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181

networks:
  default:
    name: datadog
    external: true
