version: '3.7'
services:
  selenium:
    image: selenium
    shm_size: 512m
    build:
      context: .
    ports:
      - 5901:5901
    environment:
      - KEY
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./Selenium-Automation:/home/selenium/Selenium-Automation
      - ./selenium.sh:/home/selenium/selenium.sh
#      - ./client_secret.json:/home/selenium/client_secret.json
#    privileged: true
